config/routes.rb
Rails.application.routes.draw do
  resources :publications do
    post 'likes', to: 'publications#likes'
  end

  devise_for :users
    get 'home/index'

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :publication
  belongs_to :user
end

app/models/publication.rb
class Publication < ApplicationRecord
    validates :content, presence: true

    belongs_to :user
    has_many :likes
    has_many :liking_users, :through => :likes, :source => :user

    def is_liked?(user)
        if self.liking_users.include?(user)
            true
        else
            false
        end
    end

    def add_like(user)
        Like.create(user: user, publication: self)
    end

    def remove_like(user)
        Like.where(user: user, publication: self).first.destroy
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :publications
  has_many :likes
  has_many :liked_publications, :through => :likes, :source => :publication
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permited_parameters, if: :devise_controller?
    
    protected
    def configure_permited_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @publications = Publication.all
      @publication = Publication.new
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  before_action :set_current_publication, only: [:likes]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user = current_user

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def likes
    if @publication.is_liked?(current_user)
       @publication.remove_like(current_user)
    else
      @publication.add_like(current_user)
    end
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def set_current_publication
      @publication = Publication.find(params[:publication_id])
    end
    def publication_params
      params.require(:publication).permit(:content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/home/index.html.erb
<h1>Publicaciones</h1>
<hr>
<% if user_signed_in?%>
    <%= render "publications/form", publication: @publication %>
<% else %>
    <p class="text-success">Inscribete Para Publicar</p>
<% end %>
<hr>

<div class="row">
<table class="table">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Id Publicación</th>
      <th scope="col">Publicación</th>
      <th scope="col">Likes</th>
      <th scope="col">Ver</th>
    </tr>
  </thead>
  <tbody>
    <% @publications.each do |publication| %>
    <tr>
      <th scope="row"><%= publication.id %></th>
      <td><%= publication.content %></td>
      <td>
        <!--<%= publication.likes.count %>-->
        <% if publication.is_liked?(current_user) %>
            <%= link_to '<i class="fa-solid fa-heart"></i>'.html_safe, publication_likes_path(publication), data: { "turbo-method": :post } %> 
        <% else %>
            <%= link_to '<i class="fa-regular fa-heart"></i>'.html_safe, publication_likes_path(publication), data: { "turbo-method": :post } %> 
        <% end %>
      </td>
      <td><%= link_to "Mostrar Publicación", publication %></td>
    </tr>
    <%end %>
  </tbody>
</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy4Cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <p class="notice">
        <%= notice %>
      </p>
      <p class="alert">
        <%= alert %>
      </p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= current_user.email %>:
  </div>

  <div> 
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit "Crea tu Publicación" %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <p>
    <strong>Publicación:</strong>
    <%= publication.content %>
  </p>
  <p>
    <strong>User:</strong>
    <%= publication.user_id %>
  </p>

</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publications</h1>

<div id="publications">
  <% @publications.each do |publication| %>
    <%= render publication %>
    <p>
      <%= link_to "Show this publication", publication %>
    </p>
  <% end %>
</div>

<%= link_to "New publication", new_publication_path %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", root_path %>
</div>

app/views/publications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publication %>

<div>
  <% if user_signed_in?%>
    <%= link_to "Edit this publication", edit_publication_path(@publication) %> |
  <% end%>
  <%= link_to "Back to publications", root_path %>

  <% if user_signed_in?%>
    <%= button_to "Destroy this publication", @publication, method: :delete %>
  <% end%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
        <%= link_to 'Crazy4Cats', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <% if user_signed_in? %>
                            Hola <%= current_user.email %>
                        <% else %>
                            Dale registrate o conectate
                        <% end %>
                    </a>
                    <ul class="dropdown-menu">
                    <% if user_signed_in? %>
                        <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                    <% else %>
                        <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%></li>
                    <% end %>
                    </ul>
                </li>
        </div>
    </div>
</nav>